name: GitHub CI

on: [push]

env:
  CI_REQ_DOTNET_SDK_VER: 6.0.100

jobs:
  build-windows:
    name: Build (Windows)
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{env.CI_REQ_DOTNET_SDK_VER}}

      - name: Build
        shell: pwsh
        run: |
          $msbuildPath = Split-Path (& "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -requires Microsoft.Component.MSBuild -find MSBuild\Current\Bin\amd64\MSBuild.exe | Select-Object -First 1) -Parent
          $env:PATH = $msbuildPath + ';' + $env:PATH
          .\build.ps1

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dnlib-${{ github.sha }}
          path: D:\a\dnlib\dnlib\src\bin\Release\

